apiVersion: v1
kind: Secret
metadata:
  name: :wq
  annotations:
    tekton.dev/git-0: https://github.com        # ! required
type: kubernetes.io/basic-auth          # ! required
stringData:
  username: showpune
  password: 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
